### ISSUE TITLE
Number of unverified users not reconciling between WP admin and email notifications

### ISSUE THREAD

**Issue by valuepickr** [valuepickr/Issue-Tracker#1]
When the number of pending users crosses over 150 in email, the number of unverified users in WordPress admin shows lesser number. Otherwise it matches.

**Comment by valuepickr** [comment]
Pratyush,
Issue seen at 90+emails. Not sure exactly when this started.
When I checked today 92 new registration emails are in, but unverified users count =73
the first 20 registrations (from last approval day - Nov 21 most probably) are now missing from WP
1. New registration email no 72 prakriti263@gmail.com - is there in WP
2. New registration email 73 onwards to 91 rahul@abccpl.com - not there in WP ( i checked randomly some emails for missing ...didnt check all)

Pls investigate
-Donald

**Comment by pratyushmittal** [comment]
Fixed the issue by updating the option in the plugin admin panel.
